### ISSUE TITLE
Return promise inside promise

### ISSUE THREAD

**Issue by richardsd** [hidekatsu-izuno/nashorn-promise#1]
Hi, is it possible to return a promise inside a promise. something like the following:

```
var fun = function() {
    return Promise.resolve('Original Fun);
}

var fun1 = function() {
    return Promise.resolve('fun1):
}

var fun2 = function() {
    return fun1().then(function(result) {
        assertEqual(result, 'fun1');
        return fun();
    });
}

// call fun
fun2().then(function(result) {
    assertEqual(result, 'Original Fun');
});
```

In my code, the result of calling fun2 in the thenable, is not the actual value, but instead the completable future... Am I missing something, or this is not supported? Extending this behavior would be a great feature.

**Comment by hidekatsu-izuno** [comment]
Thank you for your PR. I merged it and released version 0.1.1.
