### ISSUE TITLE
problem with nasted promises

### ISSUE THREAD

**Issue by Florian79** [hidekatsu-izuno/nashorn-promise#4]
hey guys,

apparently nasted promises are not working if depth is deeper then 3:

`
var tests = {
		nastedPromises1 : function () {
			return Promise.resolve('v1').then(function(v1){
				return Promise.resolve('v2').then(function(v2){
					return 'v3';//good
				});
			});
		},
		nastedPromises2 : function () {
			return Promise.resolve('v1').then(function(v1){
				return Promise.resolve('v2').then(function(v2){
					return Promise.resolve('v3');//bad
				});
			});
		},
		nastedPromises3 : function (http) {
			return Promise.resolve('v1').then(function(v1){
				return Promise.resolve('v2').then(function(v2){
					return Promise.resolve('v3').then(function(v3){
						return 'v4';//bad
					});
				});
			});
		},
}
tests.nastedPromises1().then(function(r){console.log(r)});//returns "v3"
tests.nastedPromises2().then(function(r){console.log(r)});//returns ""
tests.nastedPromises3().then(function(r){console.log(r)});//returns ""

`
![image](https://user-images.githubusercontent.com/5063501/66657004-5da99380-ec3f-11e9-938f-9bf8bf22ff26.png)

any idea?

cheers,
florian

**Comment by hidekatsu-izuno** [comment]
Thank you for reporting. 
I found this problem was caused by a bug. I'm fixing now. 
Please wait for a little while.
